CREATE TABLE info_test.advertisers
(
 `advertiser_id` Int32,
 `company_name` String,
 `contact_first_name` String DEFAULT \'\',
 `contact_last_name` String DEFAULT \'\',
 `email` String DEFAULT \'\',
 `primary_phone` String DEFAULT \'\',
 `cell` String DEFAULT \'\',
 `address1` String DEFAULT \'\',
 `address2` String DEFAULT \'\',
 `city` String DEFAULT \'\',
 `state` String DEFAULT \'\',
 `zip` String DEFAULT \'\',
 `active` UInt8,
 `time_zone` String,
 `account_manager_user_id` Int32 DEFAULT -1,
 `coremetrics_id` String DEFAULT \'\',
 `strict_control_group` UInt8 DEFAULT 0,
 `appnexus_segment_id` Int32 DEFAULT -1,
 `piggyback_request` Int32,
 `click_conversion_window` String,
 `allow_duplicate_orders` UInt8,
 `segmentation_active` UInt8,
 `create_time` DateTime64(6),
 `abandon_window` String,
 `invoice_conversion_window` String,
 `control_group_percentage` Decimal(2, 2),
 `strict_control_group_requests` Int32 DEFAULT -1,
 `segmentation_new_active` UInt8,
 `currency` String DEFAULT \'\',
 `google_audience_id` String DEFAULT \'\',
 `segment_piggyback` UInt8,
 `client_id` Int32 DEFAULT -1,
 `pixel_id` Int32 DEFAULT -1,
 `watermarked` UInt8,
 `tier` Int32 DEFAULT -1,
 `pixel_id_conversion` Int32 DEFAULT -1,
 `display_currency` String,
 `locale` String,
 `piggyback_tier_active` UInt8,
 `dpp_enabled` UInt8,
 `override_tt_campaign_check` UInt8,
 `event_logging_enabled` UInt8,
 `trpx_endpoint` Int32 DEFAULT -1,
 `slingshot_window` Int32,
 `slingshot_enabled` UInt8,
 `min_control_rt` Int32,
 `min_control_rto` Int32,
 `min_control_branding` Int32,
 `spx_timeout_ms` Int32 DEFAULT -1,
 `populate_order_on_conversion` UInt8,
 `facebook_page` String DEFAULT \'\',
 `facebook_page_id` Int64 DEFAULT -1,
 `week_start_day` Int16,
 `clickpass_enabled` UInt8,
 `clickpass_click_ttl` String,
 `clickpass_view_ttl` String,
 `clickpass_target_tag_id` Int16 DEFAULT -1,
 `clickpass_iframe_ttl` Int32,
 `clickpass_window` String,
 `just_registered_clickpass_ttl` Int32,
 `clickpass_iframe_delay` Int32,
 `blended_fbx_enabled` UInt8 DEFAULT 0,
 `blended_fbx_setup` UInt8 DEFAULT 0,
 `blended_fbx_click_url` String DEFAULT \'\',
 `blended_fbx_headline` String DEFAULT \'\',
 `blended_fbx_text` String DEFAULT \'\',
 `clickpass_facebook_ttl` String DEFAULT \'\',
 `news_feed_weight` Int32 DEFAULT -1,
 `right_hand_side_weight` Int32 DEFAULT -1,
 `fb_ad_account_id` Int64 DEFAULT -1,
 `use_ss_cookies` UInt8 DEFAULT 0,
 `clickpass_acquisition_ttl` String,
 `postponed_clickpass` UInt8,
 `strict_clickpass` UInt8,
 `adops_owner` String DEFAULT \'\',
 `account_health` String DEFAULT \'\',
 `publisher_enabled` UInt8 DEFAULT 0,
 `internal_cp_enabled` UInt8 DEFAULT 0,
 `apply_budget_to_total_spend` UInt8,
 `company_size` String DEFAULT \'\',
 `industry` String DEFAULT \'\',
 `billing_type_id` Int32 DEFAULT -1,
 `is_test` UInt8 DEFAULT 0,
 `logo` String DEFAULT \'\',
 `deleted` UInt8 DEFAULT 0,
 `view_conversion_window` String DEFAULT \'\',
 `product_version_id` Int32 DEFAULT -1,
 `has_products` UInt8,
 `company_url` String DEFAULT \'\',
 `update_time` DateTime64(6) DEFAULT now64(),
 `verify_email` UInt8,
 `website_review_rejection` String DEFAULT \'\',
 `facebook_tos` UInt8 DEFAULT 0,
 `tracking_pixel_status_id` Int32 DEFAULT -1,
 `conversion_pixel_status_id` Int32 DEFAULT -1,
 `website_review_status_id` Int32 DEFAULT -1,
 `facebook_page_status_id` Int32 DEFAULT -1,
 `country` String DEFAULT \'\',
 `notify_me_of_additional_services` UInt8 DEFAULT 0,
 `monthly_muv` String DEFAULT \'\',
 `temp_login_token` String DEFAULT \'\',
 `gdpr_status_id` Int32 DEFAULT -1,
 `conversion_window` String,
 `data_tier_id` Int32 DEFAULT -1,
 `api_key` String DEFAULT \'\',
 `allow_original_url_case` UInt8 DEFAULT 0,
 `invoice_email` String DEFAULT \'\',
 `status_id` Int16 DEFAULT -1,
 `invoice_terms` String DEFAULT \'\',
 `user_id` Int32 DEFAULT -1,
 `utm_argument_ignore` UInt8 DEFAULT 0
)
ENGINE = ReplicatedMergeTree(\'/clickhouse/{cluster}/tables/info_test/{uuid}/\', \'{replica}\')
PRIMARY KEY advertiser_id
ORDER BY advertiser_id
SETTINGS index_granularity = 8192
