CREATE TABLE summarydata.all_facts_single
(
 `hour` DateTime64(6),
 `advertiser_id` Int32,
 `campaign_group_id` Int32,
 `campaign_id` Int32,
 `channel_id` Int32,
 `objective_id` Int32,
 `group_id` Int32,
 `creative_id` Int32,
 `private_marketplace_id` Nullable(String),
 `country` LowCardinality(Nullable(String)),
 `metro_id` Nullable(Int32),
 `region` LowCardinality(Nullable(String)),
 `city` LowCardinality(Nullable(String)),
 `postal_code` LowCardinality(Nullable(String)),
 `domain` Nullable(String),
 `display_impressions` Int64,
 `ctv_impressions` Int64,
 `media_cost` Decimal(38, 19),
 `fee_cost` Decimal(38, 19),
 `partner_cost` Decimal(38, 19),
 `data_cost` Decimal(38, 19),
 `media_spend` Decimal(38, 19),
 `data_spend` Decimal(38, 19),
 `platform_spend` Decimal(38, 19),
 `legacy_spend` Decimal(38, 19),
 `ctv_spend` Decimal(38, 19),
 `views` Int64,
 `clicks` Int64,
 `view_conversions` Int64,
 `click_conversions` Int64,
 `view_order_value` Decimal(38, 19),
 `click_order_value` Decimal(38, 19),
 `view_impression` Int64,
 `view_viewed` Int64,
 `view_untrackable` Int64,
 `vast_start` Int64,
 `vast_firstquartile` Int64,
 `vast_midpoint` Int64,
 `vast_thirdquartile` Int64,
 `vast_complete` Int64,
 `uniques` String,
 `unlinked_spend` Decimal(38, 19),
 `supply_vendor` Nullable(String),
 `bids` Int64,
 `new_visitors` Int64,
 `raw_existing_site_visitors` String,
 `raw_new_site_visitors` String,
 `existing_users_reached` String,
 `new_users_reached` String,
 `existing_site_visitors` String,
 `new_site_visitors` String,
 `site_visitors` String,
 `new_to_file` Int64,
 `raw_visits` Int64,
 `raw_conversions` Int64,
 `visitors` String,
 `raw_order_value` Int64,
 `first_touch_visits` Int64,
 PROJECTION all_facts_single_sum_by_channel_by_day
 (
 SELECT 
 toDate(hour),
 advertiser_id,
 channel_id,
 sum(display_impressions),
 sum(ctv_impressions),
 sum(media_cost),
 sum(fee_cost),
 sum(partner_cost),
 sum(data_cost),
 sum(media_spend),
 sum(data_spend),
 sum(platform_spend),
 sum(legacy_spend),
 sum(ctv_spend),
 sum(views),
 sum(clicks),
 sum(view_conversions),
 sum(click_conversions),
 sum(view_order_value),
 sum(click_order_value),
 sum(view_impression),
 sum(view_viewed),
 sum(view_untrackable),
 sum(vast_start),
 sum(vast_firstquartile),
 sum(vast_midpoint),
 sum(vast_thirdquartile),
 sum(vast_complete),
 uniqCombinedState(uniques),
 sum(unlinked_spend),
 uniqCombinedState(supply_vendor),
 sum(bids),
 sum(new_visitors),
 uniqCombinedState(raw_existing_site_visitors),
 uniqCombinedState(raw_new_site_visitors),
 uniqCombinedState(existing_users_reached),
 uniqCombinedState(new_users_reached),
 uniqCombinedState(existing_site_visitors),
 uniqCombinedState(new_site_visitors),
 uniqCombinedState(site_visitors),
 sum(new_to_file),
 sum(raw_visits),
 sum(raw_conversions),
 uniqCombinedState(visitors),
 sum(raw_order_value),
 sum(first_touch_visits)
 GROUP BY 
 2,
 1,
 3
 ),
 PROJECTION all_facts_single_sum_by_objective_by_day
 (
 SELECT 
 toDate(hour),
 advertiser_id,
 objective_id,
 sum(display_impressions),
 sum(ctv_impressions),
 sum(media_cost),
 sum(fee_cost),
 sum(partner_cost),
 sum(data_cost),
 sum(media_spend),
 sum(data_spend),
 sum(platform_spend),
 sum(legacy_spend),
 sum(ctv_spend),
 sum(views),
 sum(clicks),
 sum(view_conversions),
 sum(click_conversions),
 sum(view_order_value),
 sum(click_order_value),
 sum(view_impression),
 sum(view_viewed),
 sum(view_untrackable),
 sum(vast_start),
 sum(vast_firstquartile),
 sum(vast_midpoint),
 sum(vast_thirdquartile),
 sum(vast_complete),
 uniqCombinedState(uniques),
 sum(unlinked_spend),
 uniqCombinedState(supply_vendor),
 sum(bids),
 sum(new_visitors),
 uniqCombinedState(raw_existing_site_visitors),
 uniqCombinedState(raw_new_site_visitors),
 uniqCombinedState(existing_users_reached),
 uniqCombinedState(new_users_reached),
 uniqCombinedState(existing_site_visitors),
 uniqCombinedState(new_site_visitors),
 uniqCombinedState(site_visitors),
 sum(new_to_file),
 sum(raw_visits),
 sum(raw_conversions),
 uniqCombinedState(visitors),
 sum(raw_order_value),
 sum(first_touch_visits)
 GROUP BY 
 2,
 1,
 3
 ),
 PROJECTION all_facts_single_sum_by_advertiser_by_day
 (
 SELECT 
 toDate(dateTrunc(\'day\', hour)),
 advertiser_id,
 sum(display_impressions),
 sum(ctv_impressions),
 sum(media_cost),
 sum(fee_cost),
 sum(partner_cost),
 sum(data_cost),
 sum(media_spend),
 sum(data_spend),
 sum(platform_spend),
 sum(legacy_spend),
 sum(ctv_spend),
 sum(views),
 sum(clicks),
 sum(view_conversions),
 sum(click_conversions),
 sum(view_order_value),
 sum(click_order_value),
 sum(view_impression),
 sum(view_viewed),
 sum(view_untrackable),
 sum(vast_start),
 sum(vast_firstquartile),
 sum(vast_midpoint),
 sum(vast_thirdquartile),
 sum(vast_complete),
 uniqCombinedState(uniques),
 sum(unlinked_spend),
 uniqCombinedState(supply_vendor),
 sum(bids),
 sum(new_visitors),
 uniqCombinedState(raw_existing_site_visitors),
 uniqCombinedState(raw_new_site_visitors),
 uniqCombinedState(existing_users_reached),
 uniqCombinedState(new_users_reached),
 uniqCombinedState(existing_site_visitors),
 uniqCombinedState(new_site_visitors),
 uniqCombinedState(site_visitors),
 sum(new_to_file),
 sum(raw_visits),
 sum(raw_conversions),
 uniqCombinedState(visitors),
 sum(raw_order_value),
 sum(first_touch_visits)
 GROUP BY 
 2,
 1
 ),
 PROJECTION all_facts_single_sum_by_campaign_group_by_day
 (
 SELECT 
 toDate(dateTrunc(\'day\', hour)),
 advertiser_id,
 campaign_group_id,
 sum(display_impressions),
 sum(ctv_impressions),
 sum(media_cost),
 sum(fee_cost),
 sum(partner_cost),
 sum(data_cost),
 sum(media_spend),
 sum(data_spend),
 sum(platform_spend),
 sum(legacy_spend),
 sum(ctv_spend),
 sum(views),
 sum(clicks),
 sum(view_conversions),
 sum(click_conversions),
 sum(view_order_value),
 sum(click_order_value),
 sum(view_impression),
 sum(view_viewed),
 sum(view_untrackable),
 sum(vast_start),
 sum(vast_firstquartile),
 sum(vast_midpoint),
 sum(vast_thirdquartile),
 sum(vast_complete),
 uniqCombinedState(uniques),
 sum(unlinked_spend),
 uniqCombinedState(supply_vendor),
 sum(bids),
 sum(new_visitors),
 uniqCombinedState(raw_existing_site_visitors),
 uniqCombinedState(raw_new_site_visitors),
 uniqCombinedState(existing_users_reached),
 uniqCombinedState(new_users_reached),
 uniqCombinedState(existing_site_visitors),
 uniqCombinedState(new_site_visitors),
 uniqCombinedState(site_visitors),
 sum(new_to_file),
 sum(raw_visits),
 sum(raw_conversions),
 uniqCombinedState(visitors),
 sum(raw_order_value),
 sum(first_touch_visits)
 GROUP BY 
 2,
 1,
 3
 )
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(hour)
ORDER BY (advertiser_id, hour)
SETTINGS index_granularity = 8192
