CREATE TABLE summarydata.all_facts_test_fields_18_9
(
 `hour` DateTime,
 `advertiser_id` Int32,
 `campaign_group_id` Int32 DEFAULT 0,
 `campaign_id` Int32 DEFAULT 0,
 `channel_id` Int32 DEFAULT 0,
 `objective_id` Int32 DEFAULT 0,
 `group_id` Int32 DEFAULT 0,
 `creative_id` Int32 DEFAULT 0,
 `private_marketplace_id` String DEFAULT \'\',
 `country` LowCardinality(String) DEFAULT \'\',
 `metro_id` Int32 DEFAULT 0,
 `region` LowCardinality(String) DEFAULT \'\',
 `city` LowCardinality(String) DEFAULT \'\',
 `postal_code` LowCardinality(String) DEFAULT \'\',
 `domain` String DEFAULT \'\',
 `display_impressions` Int64 DEFAULT 0,
 `ctv_impressions` Int64 DEFAULT 0,
 `media_cost` Decimal(18, 9) DEFAULT 0.,
 `fee_cost` Decimal(18, 9) DEFAULT 0.,
 `partner_cost` Decimal(18, 9) DEFAULT 0.,
 `data_cost` Decimal(18, 9) DEFAULT 0.,
 `media_spend` Decimal(18, 9) DEFAULT 0.,
 `data_spend` Decimal(18, 9) DEFAULT 0.,
 `platform_spend` Decimal(18, 9) DEFAULT 0.,
 `legacy_spend` Decimal(18, 9) DEFAULT 0.,
 `ctv_spend` Decimal(18, 9) DEFAULT 0.,
 `views` Int64 DEFAULT 0,
 `clicks` Int64 DEFAULT 0,
 `view_conversions` Int64 DEFAULT 0,
 `click_conversions` Int64 DEFAULT 0,
 `view_order_value` Decimal(18, 9) DEFAULT 0.,
 `click_order_value` Decimal(18, 9) DEFAULT 0.,
 `view_impression` Int64 DEFAULT 0,
 `view_viewed` Int64 DEFAULT 0,
 `view_untrackable` Int64 DEFAULT 0,
 `vast_start` Int64 DEFAULT 0,
 `vast_firstquartile` Int64 DEFAULT 0,
 `vast_midpoint` Int64 DEFAULT 0,
 `vast_thirdquartile` Int64 DEFAULT 0,
 `vast_complete` Int64 DEFAULT 0,
 `uniques_arr` Array(Nullable(String)) DEFAULT [],
 `unlinked_spend` Decimal(18, 9) DEFAULT 0.,
 `supply_vendor` String DEFAULT \'\',
 `bids` Int64 DEFAULT 0,
 `new_visitors` Int64 DEFAULT 0,
 `raw_existing_site_visitors_arr` Array(Nullable(String)) DEFAULT [],
 `raw_new_site_visitors_arr` Array(Nullable(String)) DEFAULT [],
 `existing_users_reached_arr` Array(Nullable(String)) DEFAULT [],
 `new_users_reached_arr` Array(Nullable(String)) DEFAULT [],
 `existing_site_visitors_arr` Array(Nullable(String)) DEFAULT [],
 `new_site_visitors_arr` Array(Nullable(String)) DEFAULT [],
 `site_visitors_arr` Array(Nullable(String)) DEFAULT [],
 `new_to_file` Int64 DEFAULT 0,
 `raw_visits` Int64 DEFAULT 0,
 `raw_conversions` Int64 DEFAULT 0,
 `visitors_arr` Array(Nullable(String)) DEFAULT [],
 `raw_order_value` Int64 DEFAULT 0,
 `first_touch_visits` Int64 DEFAULT 0,
 `device_type` String DEFAULT \'\',
 `last_tv_touch_clicks` Int64 DEFAULT 0,
 `last_tv_touch_views` Int64 DEFAULT 0,
 `last_tv_touch_click_conversions` Int64 DEFAULT 0,
 `last_tv_touch_view_conversions` Int64 DEFAULT 0,
 `last_tv_touch_click_order_value` Decimal(18, 9) DEFAULT 0.,
 `last_tv_touch_view_order_value` Decimal(18, 9) DEFAULT 0.,
 `last_touch_clicks` Int64 DEFAULT 0,
 `last_touch_views` Int64 DEFAULT 0,
 `last_touch_click_conversions` Int64 DEFAULT 0,
 `last_touch_click_order_value` Decimal(18, 9) DEFAULT 0.,
 `last_touch_view_order_value` Decimal(18, 9) DEFAULT 0.,
 `visits_assist` Int64 DEFAULT 0,
 `conversions_assist_click` Int64 DEFAULT 0,
 `conversions_assist_view` Int64 DEFAULT 0,
 `conversions_assist_click_order_value` Decimal(18, 9) DEFAULT 0.,
 `conversions_assist_view_order_value` Decimal(18, 9) DEFAULT 0.,
 `last_touch_view_conversions` Int64 DEFAULT 0
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(hour)
ORDER BY (advertiser_id, hour)
SETTINGS index_granularity = 8192
