CREATE TABLE summarydata.all_facts_uniques_state
(
 `hour` DateTime64(6),
 `advertiser_id` Int32,
 `campaign_group_id` Nullable(Int32),
 `campaign_id` Nullable(Int32),
 `channel_id` Nullable(Int32),
 `objective_id` Nullable(Int32),
 `group_id` Nullable(Int32),
 `creative_id` Nullable(Int32),
 `device_type` LowCardinality(Nullable(String)),
 `private_marketplace_id` Nullable(String),
 `country` LowCardinality(Nullable(String)),
 `metro_id` Nullable(Int32),
 `region` LowCardinality(Nullable(String)),
 `city` LowCardinality(Nullable(String)),
 `postal_code` LowCardinality(Nullable(String)),
 `domain` Nullable(String),
 `display_impressions` Nullable(Int64),
 `ctv_impressions` Nullable(Int64),
 `media_cost` Nullable(Decimal(38, 19)),
 `fee_cost` Nullable(Decimal(38, 19)),
 `partner_cost` Nullable(Decimal(38, 19)),
 `data_cost` Nullable(Decimal(38, 19)),
 `media_spend` Nullable(Decimal(38, 19)),
 `data_spend` Nullable(Decimal(38, 19)),
 `platform_spend` Nullable(Decimal(38, 19)),
 `legacy_spend` Nullable(Decimal(38, 19)),
 `ctv_spend` Nullable(Decimal(38, 19)),
 `views` Nullable(Int64),
 `clicks` Nullable(Int64),
 `view_conversions` Nullable(Int64),
 `click_conversions` Nullable(Int64),
 `view_order_value` Nullable(Decimal(38, 19)),
 `click_order_value` Nullable(Decimal(38, 19)),
 `view_impression` Nullable(Int64),
 `view_viewed` Nullable(Int64),
 `view_untrackable` Nullable(Int64),
 `vast_start` Nullable(Int64),
 `vast_firstquartile` Nullable(Int64),
 `vast_midpoint` Nullable(Int64),
 `vast_thirdquartile` Nullable(Int64),
 `vast_complete` Nullable(Int64),
 `uniques` AggregateFunction(uniqCombinedArray, Array(Nullable(String))),
 `unlinked_spend` Nullable(Decimal(38, 19)),
 `supply_vendor` Nullable(String),
 `bids` Nullable(Int64),
 `new_visitors` Nullable(Int64),
 `raw_existing_site_visitors` Nullable(String),
 `raw_new_site_visitors` Nullable(String),
 `existing_users_reached` AggregateFunction(uniqCombinedArray, Array(Nullable(String))),
 `new_users_reached` AggregateFunction(uniqCombinedArray, Array(Nullable(String))),
 `existing_site_visitors` Nullable(String),
 `new_site_visitors` Nullable(String),
 `site_visitors` Nullable(String),
 `new_to_file` Nullable(Int64),
 `raw_visits` Nullable(Int64),
 `raw_conversions` Nullable(Int64),
 `visitors` Nullable(String),
 `raw_order_value` Nullable(Int64),
 `first_touch_visits` Nullable(Int64)
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(hour)
ORDER BY (advertiser_id, hour)
SETTINGS index_granularity = 8192
