CREATE VIEW info.v_advertisers ON CLUSTER 'reporting-dev01'
(
 `advertiser_id` Int32,
 `company_name` String,
 `contact_first_name` Nullable(String),
 `contact_last_name` Nullable(String),
 `email` Nullable(String),
 `primary_phone` Nullable(String),
 `cell` Nullable(String),
 `address1` Nullable(String),
 `address2` Nullable(String),
 `city` Nullable(String),
 `state` Nullable(String),
 `zip` Nullable(String),
 `active` UInt8,
 `time_zone` String,
 `account_manager_user_id` Nullable(Int32),
 `coremetrics_id` Nullable(String),
 `strict_control_group` Nullable(UInt8),
 `appnexus_segment_id` Nullable(Int32),
 `piggyback_request` Int32,
 `click_conversion_window` String,
 `allow_duplicate_orders` UInt8,
 `segmentation_active` UInt8,
 `create_time` DateTime64(6),
 `abandon_window` String,
 `invoice_conversion_window` String,
 `control_group_percentage` Decimal(2, 2),
 `strict_control_group_requests` Nullable(Int32),
 `segmentation_new_active` UInt8,
 `currency` Nullable(String),
 `google_audience_id` Nullable(String),
 `segment_piggyback` UInt8,
 `client_id` Nullable(Int32),
 `pixel_id` Nullable(Int32),
 `watermarked` UInt8,
 `tier` Nullable(Int32),
 `pixel_id_conversion` Nullable(Int32),
 `display_currency` String,
 `locale` String,
 `piggyback_tier_active` UInt8,
 `dpp_enabled` UInt8,
 `override_tt_campaign_check` UInt8,
 `event_logging_enabled` UInt8,
 `trpx_endpoint` Nullable(Int32),
 `slingshot_window` Int32,
 `slingshot_enabled` UInt8,
 `min_control_rt` Int32,
 `min_control_rto` Int32,
 `min_control_branding` Int32,
 `spx_timeout_ms` Nullable(Int32),
 `populate_order_on_conversion` UInt8,
 `facebook_page` Nullable(String),
 `facebook_page_id` Nullable(Int64),
 `week_start_day` Int16,
 `clickpass_enabled` UInt8,
 `clickpass_click_ttl` String,
 `clickpass_view_ttl` String,
 `clickpass_target_tag_id` Nullable(Int16),
 `clickpass_iframe_ttl` Int32,
 `clickpass_window` String,
 `just_registered_clickpass_ttl` Int32,
 `clickpass_iframe_delay` Int32,
 `blended_fbx_enabled` Nullable(UInt8),
 `blended_fbx_setup` Nullable(UInt8),
 `blended_fbx_click_url` Nullable(String),
 `blended_fbx_headline` Nullable(String),
 `blended_fbx_text` Nullable(String),
 `clickpass_facebook_ttl` Nullable(String),
 `news_feed_weight` Nullable(Int32),
 `right_hand_side_weight` Nullable(Int32),
 `fb_ad_account_id` Nullable(Int64),
 `use_ss_cookies` Nullable(UInt8),
 `clickpass_acquisition_ttl` String,
 `postponed_clickpass` UInt8,
 `strict_clickpass` UInt8,
 `adops_owner` Nullable(String),
 `account_health` Nullable(String),
 `publisher_enabled` Nullable(UInt8),
 `internal_cp_enabled` Nullable(UInt8),
 `apply_budget_to_total_spend` UInt8,
 `company_size` Nullable(String),
 `industry` Nullable(String),
 `billing_type_id` Nullable(Int32),
 `is_test` Nullable(UInt8),
 `logo` Nullable(String),
 `deleted` Nullable(UInt8),
 `view_conversion_window` Nullable(String),
 `product_version_id` Nullable(Int32),
 `has_products` UInt8,
 `company_url` Nullable(String),
 `update_time` Nullable(DateTime64(6)),
 `verify_email` UInt8,
 `website_review_rejection` Nullable(String),
 `facebook_tos` Nullable(UInt8),
 `tracking_pixel_status_id` Nullable(Int32),
 `conversion_pixel_status_id` Nullable(Int32),
 `website_review_status_id` Nullable(Int32),
 `facebook_page_status_id` Nullable(Int32),
 `country` Nullable(String),
 `notify_me_of_additional_services` Nullable(UInt8),
 `monthly_muv` Nullable(String),
 `temp_login_token` Nullable(String),
 `gdpr_status_id` Nullable(Int32),
 `conversion_window` String,
 `data_tier_id` Nullable(Int32),
 `api_key` Nullable(String),
 `allow_original_url_case` Nullable(UInt8),
 `invoice_email` Nullable(String),
 `status_id` Nullable(Int16),
 `invoice_terms` Nullable(String),
 `user_id` Nullable(Int32),
 `utm_argument_ignore` Nullable(UInt8),
 `sales_cycle_last_1_days` Nullable(String),
 `sales_cycle_last_7_days` Nullable(String),
 `sales_cycle_last_30_days` Nullable(String)
) AS
SELECT
 advertiser_id,
 company_name,
 contact_first_name,
 contact_last_name,
 email,
 primary_phone,
 cell,
 address1,
 address2,
 city,
 state,
 zip,
 active,
 time_zone,
 account_manager_user_id,
 coremetrics_id,
 strict_control_group,
 appnexus_segment_id,
 piggyback_request,
 click_conversion_window,
 allow_duplicate_orders,
 segmentation_active,
 create_time,
 abandon_window,
 invoice_conversion_window,
 control_group_percentage,
 strict_control_group_requests,
 segmentation_new_active,
 currency,
 google_audience_id,
 segment_piggyback,
 client_id,
 pixel_id,
 watermarked,
 tier,
 pixel_id_conversion,
 display_currency,
 locale,
 piggyback_tier_active,
 dpp_enabled,
 override_tt_campaign_check,
 event_logging_enabled,
 trpx_endpoint,
 slingshot_window,
 slingshot_enabled,
 min_control_rt,
 min_control_rto,
 min_control_branding,
 spx_timeout_ms,
 populate_order_on_conversion,
 facebook_page,
 facebook_page_id,
 week_start_day,
 clickpass_enabled,
 clickpass_click_ttl,
 clickpass_view_ttl,
 clickpass_target_tag_id,
 clickpass_iframe_ttl,
 clickpass_window,
 just_registered_clickpass_ttl,
 clickpass_iframe_delay,
 blended_fbx_enabled,
 blended_fbx_setup,
 blended_fbx_click_url,
 blended_fbx_headline,
 blended_fbx_text,
 clickpass_facebook_ttl,
 news_feed_weight,
 right_hand_side_weight,
 fb_ad_account_id,
 use_ss_cookies,
 clickpass_acquisition_ttl,
 postponed_clickpass,
 strict_clickpass,
 adops_owner,
 account_health,
 publisher_enabled,
 internal_cp_enabled,
 apply_budget_to_total_spend,
 company_size,
 industry,
 billing_type_id,
 is_test,
 logo,
 deleted,
 view_conversion_window,
 product_version_id,
 has_products,
 company_url,
 update_time,
 verify_email,
 website_review_rejection,
 facebook_tos,
 tracking_pixel_status_id,
 conversion_pixel_status_id,
 website_review_status_id,
 facebook_page_status_id,
 country,
 notify_me_of_additional_services,
 monthly_muv,
 temp_login_token,
 gdpr_status_id,
 conversion_window,
 data_tier_id,
 api_key,
 allow_original_url_case,
 invoice_email,
 status_id,
 invoice_terms,
 user_id,
 utm_argument_ignore,
 avg_sales_cycle_time_1_day_string AS sales_cycle_last_1_days,
 avg_sales_cycle_time_7_day_string AS sales_cycle_last_7_days,
 avg_sales_cycle_time_30_day_string AS sales_cycle_last_30_days
FROM info.advertisers AS a
LEFT JOIN
(
 SELECT
 sc.day,
 sc.advertiser_id,
 sc.avg_sales_cycle_time_30_day_string,
 sc.avg_sales_cycle_time_7_day_string,
 sc.avg_sales_cycle_time_1_day_string
 FROM summarydata.sales_cycle_averages_by_advertiser_id AS sc
 WHERE sc.day = (
 SELECT max(sc_date.day) AS max
 FROM summarydata.sales_cycle_averages_by_advertiser_id AS sc_date
 WHERE (sc_date.day >= (today() - toIntervalDay(2))) AND (sc_date.day < (today() + toIntervalDay(1)))
 )
 LIMIT 1 BY
 sc.day,
 sc.advertiser_id
) AS sc_avg ON sc_avg.advertiser_id = a.advertiser_id
